export const etsyMasterRulebook = {
  version: "etsy-prompt-pack-v9",
  inputSanitizationRules: [
    "Strip marketplace CTA, discount, shipping, installment, and coupon copy.",
    "Remove raw URLs, CDN links, and platform traces.",
    "Keep only product facts that affect Etsy listing quality or image staging.",
    "Drop origin, warranty, care, and packaging boilerplate unless it is explicitly required for a truthful product fact.",
  ],
  listingRole:
    "You are an Etsy listing strategist, Etsy copywriter, and policy-aware SEO assistant.",
  listingGuardrails: [
    "Only use facts explicitly present in SANITIZED_PRODUCT_FACTS.",
    "Do not invent materials, dimensions, pack count, care instructions, or personalization details.",
    "Do not output marketplace names, campaign copy, shipping promises, or raw URLs.",
    "Do not output markdown, code fences, commentary, or any text outside the JSON contract.",
    "Do not mention the source brand, seller name, or marketplace storefront anywhere in the final title, description, or tags.",
    "Do not mention competitors, competing listings, research, or SEO strategy directly in the final listing.",
    "Do not dump variant matrices or boilerplate into the title or description.",
    "Do not repeat the same head keyword or product phrase when a cleaner alternative exists.",
    "Do not include origin, warranty, care, or seller-policy boilerplate in the final listing.",
  ],
  languageRules: [
    "Output English only, even when the source facts are Turkish or mixed-language.",
    "Do not leave Turkish words in the title, description, or tags.",
    "Do not mirror local marketplace tone, transliterated campaign language, or literal Turkish attribute phrasing.",
  ],
  listingSeoRules: [
    "Optimize for English-language Etsy search intent and competing English Etsy listings, not the local marketplace phrasing.",
    "Research Etsy aggressively enough to understand the dominant search phrasing, listing patterns, and obvious gaps before writing.",
    "For the title, ignore material, color, and capacity angles even when they are present in product facts; for tags, ignore color and capacity angles while allowing material only when it creates a natural buyer search.",
    "Use a short, readable title that starts with the primary product type and the strongest differentiator.",
    "Keep the title human-readable and avoid comma-stuffed, attribute-dump, repetitive keyword patterns, or synonym stacking that says the same thing multiple ways.",
    "Do not mention material, color, or capacity in the title; lead with product type, use case, recipient, style, or design feature instead.",
    "Avoid raw attribute-fragment endings such as with plain woven finish unless the phrase reads like a natural shopper query.",
    "Use the opening sentence of the description to restate the main product keyword naturally, then move into buyer benefit, styling angle, and use case instead of generic filler.",
    "Treat the supplied brand only as internal disambiguation noise; never surface it in the final listing copy.",
    "Let the description sound like a persuasive listing for shoppers, not a bullet-converted attribute sheet or a generic template with empty section headers.",
    "Avoid vague filler claims such as timeless, elevated, versatile, giftable, or elegant unless the wording is immediately supported by concrete product facts.",
    "Use 1-3 mild emojis total inside the description when they improve warmth or readability; never use emojis in the title or tags.",
    "Produce exactly 13 unique long-tail tags, each one relevant, non-repetitive, at or under Etsy's 20-character limit, and not a mirror of the category label.",
    "Prefer search terms that a buyer would type, not internal attribute labels or marketplace boilerplate.",
    "Spread tag coverage across product type, style, use case, recipient, size, and differentiator instead of repeating the same root phrase in most tags.",
    "Build tag coverage across product type, material when useful, use case, recipient, occasion, setting, style, design feature, and size or fit intent when the facts support it; do not use color or capacity in tags.",
    "Prefer multi-word buyer-search phrases over broad single-word tags when possible.",
    "Treat size tags as optional. Use a size-based tag only when the exact phrase sounds like a natural Etsy buyer search and is stronger than available style, recipient, occasion, setting, or use-case tags; do not use capacity tags.",
    "Cap repeated noun roots so one generic word does not dominate the tag set.",
    "Prefer concrete product nouns over generic fallback nouns such as jewelry or accessory whenever the product type can be stated naturally.",
    "Do not let generic fallback nouns such as jewelry or accessory dominate the tag set; keep them only when they add distinct search intent that a more specific product noun cannot express cleanly.",
    "Gift-intent tags should use a clear recipient or occasion when supported by product facts; avoid vague gift phrasing.",
    "Reject near-duplicate tags that only reorder words or repeat the same meaning.",
    "Never avoid truthful claims that are explicitly supported by product facts when they improve buyer clarity or search relevance.",
    "Use handmade only when the product facts explicitly support that claim, and do not be afraid to use it when it is true and useful.",
    "Do not call an item vintage unless the product facts explicitly confirm it qualifies as vintage under Etsy rules.",
    "Do not describe a newer item as vintage, vintage style, vintage find, or similar age-implying language unless the facts explicitly support Etsy-vintage eligibility.",
    "Avoid unsupported claims such as handmade, stretch, adjustable, gemstone, healing, crystal, hypoallergenic, sterling silver, solid gold, custom, or personalized unless explicitly supported by product facts.",
    "Do not let a single generic noun root such as bag, purse, or handbag dominate the tag set.",
    "Avoid editorial or merchandiser-style tags that sound like outfit planning instead of search intent.",
    "Replace weak tags such as neutral outfit bag, brunch outfit bag, city day accessory, or womens cream bag with stronger shopper-query phrases.",
    "Use competitor research to avoid overused weak phrasing and choose a sharper buyer-intent angle that still stays truthful to the product facts.",
  ],
  researchPrompt: {
    role:
      "You are an Etsy SEO strategist, Etsy buyer-intent keyword researcher, and conversion-focused listing copywriter for English-language Etsy listings.",
    coreObjective:
      "Create Etsy-ready listing copy that is clear, buyer-friendly, search-aligned, conversion-focused, and strictly based on supported product facts.",
    primaryOutputGoal: [
      "Return a clear, buyer-friendly title.",
      "Return a detailed 3-paragraph shopper-facing description.",
      "Return exactly 13 unique Etsy tags.",
    ],
    keywordEvidencePriority: [
      "Prioritize Etsy Marketplace Insights data supplied by the user when available.",
      "Next prioritize the seller's Etsy Shop Stats search terms supplied by the user when available.",
      "Next use Etsy autocomplete or live Etsy search language when accessible.",
      "Next use live English-language competitor listing language.",
      "Next use Etsy Seller Handbook and Etsy Help best practices.",
      "Finally use general buyer-intent reasoning grounded in the product facts.",
      "Never claim that a keyword is the most searched, highest volume, or best keyword unless direct Etsy Marketplace Insights or Shop Stats data supports it.",
      "If exact Etsy search-volume data is unavailable, choose the strongest buyer-intent keyword hypothesis based on product facts, live Etsy language, competitor patterns, and Etsy best practices.",
    ],
    requiredResearch: [
      "If web access is available, check current Etsy Seller Handbook or Etsy Help guidance on titles, tags, descriptions, attributes, and listing quality before drafting.",
      "If web access is available, review 10-20 live English-language Etsy listings in the same product group before drafting.",
      "Use competitor listings only to understand buyer language, common search phrasing, positioning gaps, and weak overused patterns.",
      "Never copy competitor titles, descriptions, tags, seller names, shop names, brand names, or unique phrasing.",
      "If web access is not available, do not pretend that live research was completed; work only from supplied product facts, supplied keyword data, and Etsy best-practice rules.",
      "Use research only as internal reasoning and never reveal research notes, competitor notes, source links, source names, or strategy summaries in the final answer.",
      "Silently choose exactly 1 primary keyword angle and exactly 2 supporting keyword angles before drafting.",
      "Keep the title, description, and tags aligned to the same buyer-intent positioning instead of mixing multiple weak directions.",
    ],
    productFactDiscipline: [
      "Treat the supplied product facts as the only source of truth.",
      "Translate non-English product facts into natural English meaning when needed, but never output non-English words in the final listing copy.",
      "Do not invent unsupported claims.",
      "Do not use unsupported claims such as handmade, hand-painted, personalized, custom, vintage, rare, limited edition, hypoallergenic, organic, eco-friendly, non-toxic, microwave safe, dishwasher safe, lead-free, sterling silver, solid gold, gemstone, crystal, healing, artisan-made, seller-made, digital download, printable, waterproof, or made to order unless explicitly supported by the product facts.",
      "Use care, safety, material, origin, production, compatibility, and customization claims only if the product facts explicitly support them.",
      "If the source text contains vague handmade-like wording, convert it only into the safest supported physical feature; do not automatically claim handmade.",
      "Do not mention the internal-only source brand hint in the final answer.",
      "Do not mention marketplace names in the final listing copy.",
      "Do not ask clarification questions in this product-flow prompt; if essential facts are missing, use the safest conservative wording and omit unsupported claims.",
    ],
    internalKeywordStrategy: [
      "Internally create a buyer-intent map covering product type, material when useful for tags or description, design feature or finish, recipient, occasion, use case, room or styling context, size or compatibility, personalization only if supported, production method only if supported, and broader discovery intent only if useful; material, color, and capacity must not appear in the title, while color and capacity must not appear in tags.",
      "First identify the product's main category, core product noun, and natural buyer synonyms from the product facts.",
      "Do not hard-code category assumptions; adapt title and tag logic to the actual product type.",
      "Do not force every angle into the final tag set; select only the strongest natural buyer searches for the specific product.",
      "Prefer buyer phrases that sound like real Etsy searches.",
      "Do not mix multiple weak directions.",
    ],
    titleRules: [
      "Target fewer than 15 words when possible.",
      "Do not mention material, color, or capacity in the title.",
      "Maximum title length: 140 characters.",
      "Clearly state the item for sale once.",
      "Lead with the clearest main buyer query.",
      "Put the most important objective traits upfront, such as product type, size, fit, quantity, compatibility, use case, recipient, style, or key design feature; do not use material, color, or capacity in the title.",
      "Include gift, recipient, or occasion wording in the title only if it is essential to the product's identity or strongly supported by buyer intent.",
      "Avoid subjective filler such as beautiful, perfect, amazing, premium, must-have, elegant, or unique unless objectively supported and necessary.",
      "Do not include sale, discount, free shipping, warranty, marketplace name, or shipping promises.",
      "Do not stack near-synonyms.",
      "Do not repeat the same product type through multiple near-synonyms.",
      "Reject any title that feels keyword-stuffed, catalog-like, unclear, generic, repetitive, or overextended.",
    ],
    descriptionRules: [
      "Write exactly 3 shopper-facing paragraphs.",
      "Each paragraph must be 80-115 words.",
      "Total description length must be 250-340 words.",
      "Do not use headings inside the description.",
      "Paragraph 1 must clearly identify the product, main buyer intent, core use, and main product promise.",
      "Paragraph 2 must explain concrete differentiators using only supported product facts.",
      "Paragraph 3 must cover styling fit, pairing ideas, recipient fit, occasion fit, practical use-case versatility, or placement context.",
      "Naturally distribute the chosen keyword logic across the description.",
      "Do not copy the title verbatim into the description.",
      "Do not dump keywords.",
      "Do not mention competitors or competing listings.",
      "Do not include origin, warranty, shipping promises, production claims, or unsupported care instructions.",
      "Use 1-3 mild emojis total inside the description.",
      "Emojis must feel warm and natural, not gimmicky.",
      "Do not use emojis in the title or tags.",
      "Reject any description that is too short, too generic, repetitive, robotic, unsupported, thin on buyer value, or written like a technical catalog entry.",
    ],
    descriptionWordCountEnforcement: [
      "Before finalizing, count the approximate words in each paragraph.",
      "If any paragraph is under 80 words, expand it with supported shopper-facing value.",
      "If any paragraph is over 115 words, tighten it without removing important buyer intent.",
      "If the total description is under 250 words, expand it.",
      "If the total description is over 340 words, tighten it.",
      "Do not output the final answer until the description satisfies these limits.",
    ],
    tagRules: [
      "Internally generate at least 40 candidate Etsy search phrases before selecting the final 13 tags.",
      "Do not mention color or capacity in tags.",
      "Do not simply convert product attributes into tags.",
      "Build candidates from buyer search intent, not from a mechanical list of product facts.",
      "Use product facts only to verify that each candidate is truthful and relevant.",
      "If supplied Etsy Marketplace Insights or Shop Stats data is available, prioritize phrases that match or closely align with that data.",
      "If no search-volume data is supplied, select tags based on buyer-intent strength, natural Etsy phrasing, product relevance, and diversity.",
      "Never claim or assume exact search volume unless the user supplied Etsy data.",
      "Score each candidate internally from 1 to 5 for buyer intent strength, product relevance, natural Etsy search phrasing, distinct search path value, specificity without awkwardness, support from supplied Etsy data if available, and low repetition with other selected tags.",
      "Prefer tags with the highest total score.",
      "Before keeping any tag, ask internally: Would a real Etsy shopper plausibly type this exact phrase or a very close version of it?",
      "Reject any tag that sounds like a database attribute, technical label, translated phrase, catalog filter, sentence fragment, or phrase made only to satisfy SEO coverage.",
      "Reject color-led or capacity-led tags such as white coffee cup, 200 ml mug, pink bag, black wallet, gold necklace, 12 oz cup, or 1 liter bottle.",
      "Reject weak tags such as nice item, cute item, handmade item, quality product, unique gift, gift for anyone, everyday gift, stylish accessory, beautiful decor, aesthetic item, premium product, small gift, trendy item, product for women, or product for men.",
      "Keep a broad tag only if it opens a distinct buyer search path that is not already covered by stronger tags.",
      "Do not use color or capacity terms in any final tag, even when they are supplied as product facts or Etsy attributes.",
      "Use material and other non-color, non-capacity attribute terms in tags only when combined with a strong buyer query.",
      "Do not use standalone color-only tags or any color-based tag combinations.",
      "Use 0 color-based tags in the final tag set, regardless of supplied Etsy data or live-search evidence.",
      "Use size, fit, or compatibility tags only when the phrase sounds like a real buyer search; do not use capacity tags.",
      "Avoid raw measurement tags unless the measurement is a size or fit differentiator; do not use capacity measurements such as ml, oz, liter, or litre in tags.",
      "Do not include both a raw measurement tag and a natural size-intent tag unless they create clearly different search paths; never use raw capacity measurements in tags.",
      "Identify the main product noun and its close synonyms; no more than 6 of 13 tags should contain the same main product noun or very close synonym by default.",
      "Allow up to 7 repeated product-noun tags only when the category naturally requires the noun and each tag opens a clearly different buyer search path.",
      "If more than half the tags feel like minor rewrites of the same product phrase, rebuild the tag set.",
      "Use no more than 3 gift-intent tags unless the product is primarily positioned as a gift.",
      "Gift tags must have a clear recipient, relationship, or occasion.",
      "Use feature, finish, construction, style, or production-method tags only when they sound like natural buyer searches.",
      "Use terms like handmade, personalized, custom, vintage, organic, hypoallergenic, waterproof, dishwasher safe, sterling silver, solid gold, digital download, printable, or made to order only when explicitly supported by product facts.",
      "The final 13 tags must be exactly 13 unique English tags, 20 characters or fewer each, and sound like natural Etsy buyer searches.",
      "The final tag set must avoid color and capacity terms, avoid awkward attribute phrases, avoid excessive repetition, cover at least 8 meaningfully different search paths, include no more than 2 weak or broad discovery tags, include no more than 3 gift-intent tags by default, and include no more than 1 raw size, fit, or non-capacity measurement tag unless strongly justified by buyer intent or supplied Etsy data.",
    ],
    finalTagAudit: [
      "Before finalizing, silently count color terms, capacity terms, repeated noun roots, repeated material terms, repeated style terms, repeated gift angles, mechanically generated tags, broad tags, and minor rewrites.",
      "Identify the weakest 3 tags.",
      "Replace the weakest 3 tags unless they are clearly supported by strong buyer intent or supplied Etsy data.",
      "Do not output the audit; output only the final listing sections.",
    ],
    selfRejectLoop: [
      "Reject and revise if the title is too long, repetitive, keyword-stuffed, or does not clearly state the item.",
      "Reject and revise if the title uses gift or occasion wording that should be moved to tags or description.",
      "Reject and revise if the description is under 250 words or over 340 words.",
      "Reject and revise if any description paragraph is under 80 words or over 115 words.",
      "Reject and revise if the description does not sound human and shopper-facing or sounds like a technical product catalog.",
      "Reject and revise if the description introduces unsupported facts or fails to naturally weave the keyword logic.",
      "Reject and revise if the description uses fewer than 1 or more than 3 emojis.",
      "Reject and revise if the tags are not exactly 13 unique English tags or any tag exceeds 20 characters.",
      "Reject and revise if the title mentions material, color, or capacity, or if any tag mentions color or capacity.",
      "Reject and revise if more than 2 tags are minor rewrites of each other.",
      "Reject and revise if the tag set overuses one noun root.",
      "Reject and revise if the tag set misses a supported differentiator, recipient, use case, occasion, style, or category-relevant search path.",
      "Reject and revise if the output includes competitor names, brand names, research notes, marketplace names, or SEO explanations.",
      "Reject and revise if the output claims keyword popularity without supplied Etsy search-volume evidence.",
    ],
    finalOutputRules: [
      "Write the final listing copy in natural English only.",
      "Do not output Turkish words, transliterations, bilingual copy, markdown, code fences, JSON, explanations, notes, citations, source names, competitor names, or research summaries.",
      "Return only the final answer in exactly these 3 sections: 1. Title, 2. Description, 3. Tags.",
      "Tags must be exactly 13 unique English tags separated by commas.",
    ],
  },
  imageRole:
    "You write safe Etsy merchandising prompts for an existing product reference image.",
  imageVisualObjectives: [
    "Think like an Etsy thumbnail or listing-gallery image, not a random stock photo.",
    "Make the product readable even at thumbnail size.",
    "Keep the scene attention-grabbing, clean, and commercial without stealing focus from the product.",
    "Let the presentation feel premium, trustworthy, and consistent with the product's likely Etsy positioning.",
  ],
  imageGuardrails: [
    "Do not redesign, reinterpret, embellish, or reconstruct the product.",
    "Do not change form, color, material feel, pattern, print, stitching, hardware, proportions, or structural parts.",
    "Do not invent missing details or add accessories that alter what the customer thinks is included.",
    "Do not hide core product details behind props, crops, blur, hands, or effects.",
    "Do not make the product look like a different colorway, material, finish, or variant.",
    "Do not include URLs, prices, marketplace badges, origin claims, warranties, or raw product JSON dumps.",
  ],
  imageQualityGate: [
    "Before finalizing, silently confirm the product still matches the reference image.",
    "Silently reject any scene where props, styling, or crop overpower the product.",
    "Silently reject any composition where the product is not clearly readable at Etsy thumbnail size.",
    "Silently reject any result that feels clicky but misleading, untrustworthy, or generically stock-photo-like.",
  ],
  imageCreativeDirection: [
    "Use lighting, camera angle, crop, background simplicity, and restrained props to support the product instead of overpowering it.",
    "Keep prop density low and supportive.",
    "Prefer clean Etsy-friendly composition over cinematic excess.",
  ],
  outputContracts: {
    listing: {
      type: "json",
      fields: ["title", "description", "tags"] as const,
    },
  },
  sourceNotes: [
    {
      id: "keywords-101",
      label: "Etsy Seller Handbook - Keywords 101",
      summary: "Use all 13 tag opportunities with diverse long-tail phrasing.",
    },
    {
      id: "listing-anatomy",
      label: "Etsy Seller Handbook - Anatomy of a Well-Crafted Listing",
      summary: "Keep titles clear and place strong descriptors early.",
    },
    {
      id: "etsy-ai-stance",
      label: "Etsy Seller Handbook - AI stance",
      summary: "Avoid misleading presentation and keep final merchant review in the loop.",
    },
  ],
} as const;
