name = "dropshipingtakip2-api"
main = "src/worker.ts"
compatibility_date = "2026-03-20"

[[d1_databases]]
binding = "DB"
database_name = "dropshipingtakip2-prod"
database_id = "384c8b3b-2382-47ff-bdae-8a7a8fa82c96"
migrations_dir = "drizzle"

[[queues.producers]]
binding = "REFRESH_QUEUE"
queue = "dropshipingtakip2-refresh"

[[queues.consumers]]
queue = "dropshipingtakip2-refresh"
max_batch_size = 25
max_batch_timeout = 30

[triggers]
crons = ["0 * * * *"]

[env.dev]
name = "dropshipingtakip2-api-dev"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "dropshipingtakip2-dev"
database_id = "5cb5ded7-cbf6-4d14-a307-6bfee2030366"
migrations_dir = "drizzle"

[[env.dev.queues.producers]]
binding = "REFRESH_QUEUE"
queue = "dropshipingtakip2-refresh-dev"

[[env.dev.queues.consumers]]
queue = "dropshipingtakip2-refresh-dev"
max_batch_size = 25
max_batch_timeout = 30
